import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { generateReleaseNotes } from '../dist/release.js';
function git(root,...args){return execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trim();}
async function repo(){const root=await mkdtemp(join(tmpdir(),'aunoforge-release-'));git(root,'init');git(root,'config','user.email','t@example.com');git(root,'config','user.name','T');await writeFile(join(root,'x'),'0');git(root,'add','.');git(root,'commit','-m','chore: initial');git(root,'tag','v0.1.0');for(const [n,msg] of [[1,'fix: prevent player resize'],[2,'feat: add django recipe'],[3,'security: harden redirect validation']]){await writeFile(join(root,'x'),String(n));git(root,'add','.');git(root,'commit','-m',msg);}return root;}
async function repoWithMessages(messages){const root=await mkdtemp(join(tmpdir(),'aunoforge-release-intelligence-'));git(root,'init');git(root,'config','user.email','t@example.com');git(root,'config','user.name','T');await writeFile(join(root,'x'),'0');git(root,'add','.');git(root,'commit','-m','chore: initial');git(root,'tag','v0.1.0');let value=1;for(const message of messages){await writeFile(join(root,'x'),String(value++));git(root,'add','.');git(root,'commit','-m',message);}return root;}

test('release notes classify conventional commits deterministically', async()=>{const root=await repo();const result=await generateReleaseNotes({root,from:'v0.1.0'});assert.match(result.markdown,/### Fixed[\s\S]*prevent player resize/);assert.match(result.markdown,/### Added[\s\S]*add django recipe/);assert.match(result.markdown,/### Security[\s\S]*harden redirect/);assert.match(result.markdown,/Compatibility/);});

test('release notes optionally include merged PR and contributor metadata', async()=>{const root=await repo();const reader={listMergedPullRequestsSince:async()=>[{number:8,title:'feat: contributor recipe',body:'',url:'u',labels:['recipe'],mergedAt:'2026-09-01T00:00:00Z',author:'alice',breaking:false}]};const result=await generateReleaseNotes({root,from:'v0.1.0',github:{reader,owner:'o',repo:'r',since:'2026-08-01T00:00:00Z'}});assert.match(result.markdown,/#8/);assert.match(result.markdown,/@alice/);});

test('release intelligence exposes deterministic categories and minor guidance from commit evidence', async()=>{const root=await repo();const result=await generateReleaseNotes({root,from:'v0.1.0'});assert.ok(result.dataset,'release dataset must be present');assert.equal(result.dataset.recommendedBump,'minor');assert.deepEqual(result.dataset.categories.Features.map(change=>change.title),['add django recipe']);assert.deepEqual(result.dataset.categories.Fixes.map(change=>change.title),['prevent player resize']);assert.deepEqual(result.dataset.categories.Security.map(change=>change.title),['harden redirect validation']);assert.deepEqual(result.dataset.categories.Breaking,[]);assert.deepEqual(result.dataset.categories.Maintenance,[]);for(const category of ['Features','Fixes','Security']){for(const change of result.dataset.categories[category]){assert.equal(change.source,'commit');assert.match(change.evidence,/^commit:/);}}});

test('release intelligence recommends major when verified breaking commit evidence exists', async()=>{const root=await repoWithMessages(['fix: small repair','feat!: remove legacy API']);const result=await generateReleaseNotes({root,from:'v0.1.0'});assert.ok(result.dataset,'release dataset must be present');assert.equal(result.dataset.recommendedBump,'major');assert.deepEqual(result.dataset.categories.Breaking.map(change=>change.title),['remove legacy API']);assert.deepEqual(result.dataset.categories.Features,[]);assert.deepEqual(result.dataset.categories.Fixes.map(change=>change.title),['small repair']);});

test('release intelligence recommends patch for maintenance-only release-worthy changes', async()=>{const root=await repoWithMessages(['docs: refresh operator guide','chore: refresh fixtures']);const result=await generateReleaseNotes({root,from:'v0.1.0'});assert.ok(result.dataset,'release dataset must be present');assert.equal(result.dataset.recommendedBump,'patch');assert.deepEqual(result.dataset.categories.Maintenance.map(change=>change.title),['refresh fixtures','refresh operator guide']);assert.deepEqual(result.dataset.categories.Features,[]);assert.deepEqual(result.dataset.categories.Breaking,[]);});

test('release intelligence classifies pull requests by label then title then maintenance fallback', async()=>{const root=await repo();const reader={listMergedPullRequestsSince:async()=>[
  {number:21,title:'fix: title conflicts with feature label',body:'',labels:['Feature'],mergedAt:'2026-09-02T00:00:00Z',author:'zoe',breaking:false},
  {number:22,title:'feat: title conflicts with security label',body:'',labels:['security'],mergedAt:'2026-09-03T00:00:00Z',author:'alice',breaking:false},
  {number:23,title:'fix: title fallback repair',body:'',labels:[],mergedAt:'2026-09-04T00:00:00Z',author:'bob',breaking:false},
  {number:24,title:'misc housekeeping',body:'',labels:[],mergedAt:'2026-09-05T00:00:00Z',breaking:false},
  {number:25,title:'feat: title conflicts with breaking label',body:'',labels:['BREAKING'],mergedAt:'2026-09-06T00:00:00Z',author:'carol',breaking:true}
]};const result=await generateReleaseNotes({root,from:'v0.1.0',github:{reader,owner:'o',repo:'r',since:'2026-08-01T00:00:00Z'}});const byPr=new Map(Object.values(result.dataset.categories).flat().filter(change=>change.pullRequest).map(change=>[change.pullRequest,change]));assert.equal(byPr.get(21)?.category,'Features');assert.equal(byPr.get(21)?.evidence,'label:feature');assert.equal(byPr.get(22)?.category,'Security');assert.equal(byPr.get(22)?.evidence,'label:security');assert.equal(byPr.get(23)?.category,'Fixes');assert.equal(byPr.get(23)?.evidence,'title:fix');assert.equal(byPr.get(24)?.category,'Maintenance');assert.equal(byPr.get(24)?.evidence,'fallback:maintenance');assert.equal(byPr.get(25)?.category,'Breaking');assert.equal(byPr.get(25)?.evidence,'label:breaking');assert.equal(result.dataset.recommendedBump,'major');assert.deepEqual(result.dataset.contributors,['alice','bob','carol','zoe']);});
