import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { generateReleaseNotes } from '../dist/release.js';
function git(root,...args){return execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trim();}
async function repo(){const root=await mkdtemp(join(tmpdir(),'aunoforge-release-'));git(root,'init');git(root,'config','user.email','t@example.com');git(root,'config','user.name','T');await writeFile(join(root,'x'),'0');git(root,'add','.');git(root,'commit','-m','chore: initial');git(root,'tag','v0.1.0');for(const [n,msg] of [[1,'fix: prevent player resize'],[2,'feat: add django recipe'],[3,'security: harden redirect validation']]){await writeFile(join(root,'x'),String(n));git(root,'add','.');git(root,'commit','-m',msg);}return root;}
async function repoWithMessages(messages){const root=await mkdtemp(join(tmpdir(),'aunoforge-release-intelligence-'));git(root,'init');git(root,'config','user.email','t@example.com');git(root,'config','user.name','T');await writeFile(join(root,'x'),'0');git(root,'add','.');git(root,'commit','-m','chore: initial');git(root,'tag','v0.1.0');let value=1;for(const message of messages){await writeFile(join(root,'x'),String(value++));git(root,'add','.');git(root,'commit','-m',message);}return root;}

test('release notes classify conventional commits deterministically', async()=>{const root=await repo();const result=await generateReleaseNotes({root,from:'v0.1.0'});assert.match(result.markdown,/### Fixed[\s\S]*prevent player resize/);assert.match(result.markdown,/### Added[\s\S]*add django recipe/);assert.match(result.markdown,/### Security[\s\S]*harden redirect/);assert.match(result.markdown,/Compatibility/);});

test('release notes optionally include merged PR and contributor metadata', async()=>{const root=await repo();const reader={listMergedPullRequestsSince:async()=>[{number:8,title:'feat: contributor recipe',body:'',url:'u',labels:['recipe'],mergedAt:'2026-09-01T00:00:00Z',author:'alice',breaking:false}]};const result=await generateReleaseNotes({root,from:'v0.1.0',github:{reader,owner:'o',repo:'r',since:'2026-08-01T00:00:00Z'}});assert.match(result.markdown,/#8/);assert.match(result.markdown,/@alice/);});

test('release intelligence exposes deterministic categories and minor guidance from commit evidence', async()=>{const root=await repo();const result=await generateReleaseNotes({root,from:'v0.1.0'});assert.ok(result.dataset,'release dataset must be present');assert.equal(result.dataset.recommendedBump,'minor');assert.deepEqual(result.dataset.categories.Features.map(change=>change.title),['add django recipe']);assert.deepEqual(result.dataset.categories.Fixes.map(change=>change.title),['prevent player resize']);assert.deepEqual(result.dataset.categories.Security.map(change=>change.title),['harden redirect validation']);assert.deepEqual(result.dataset.categories.Breaking,[]);assert.deepEqual(result.dataset.categories.Maintenance,[]);for(const category of ['Features','Fixes','Security']){for(const change of result.dataset.categories[category]){assert.equal(change.source,'commit');assert.match(change.evidence,/^commit:/);}}});

test('release intelligence recommends major when verified breaking commit evidence exists', async()=>{const root=await repoWithMessages(['fix: small repair','feat!: remove legacy API']);const result=await generateReleaseNotes({root,from:'v0.1.0'});assert.ok(result.dataset,'release dataset must be present');assert.equal(result.dataset.recommendedBump,'major');assert.deepEqual(result.dataset.categories.Breaking.map(change=>change.title),['remove legacy API']);assert.deepEqual(result.dataset.categories.Features,[]);assert.deepEqual(result.dataset.categories.Fixes.map(change=>change.title),['small repair']);});

test('release intelligence recommends patch for maintenance-only release-worthy changes', async()=>{const root=await repoWithMessages(['docs: refresh operator guide','chore: refresh fixtures']);const result=await generateReleaseNotes({root,from:'v0.1.0'});assert.ok(result.dataset,'release dataset must be present');assert.equal(result.dataset.recommendedBump,'patch');assert.deepEqual(result.dataset.categories.Maintenance.map(change=>change.title),['refresh fixtures','refresh operator guide']);assert.deepEqual(result.dataset.categories.Features,[]);assert.deepEqual(result.dataset.categories.Breaking,[]);});
